
export const CATEGORY_MAP = {
    // Ofis & Kırtasiye
    'Ajanda': 'ofis-kirtasiye',
    'Ataş': 'ofis-kirtasiye',
    'Bant & Bant Makinesi': 'ofis-kirtasiye',
    'Cetvel': 'ofis-kirtasiye',
    'Defter': 'ofis-kirtasiye',
    'Delgeç': 'ofis-kirtasiye',
    'Dosya': 'ofis-kirtasiye',
    'Etiket': 'ofis-kirtasiye',
    'Fotokopi & Baskı Kağıtları': 'ofis-kirtasiye',
    'Hesap Makinesi': 'ofis-kirtasiye',
    'Kalemlik & Ataşlık': 'ofis-kirtasiye',
    'Kaşe ve Istanpa': 'ofis-kirtasiye',
    'Kaşe ve Istampa': 'ofis-kirtasiye',
    'Masaüstü Organizer': 'ofis-kirtasiye',
    'Not Kağıtları ve Bloknot': 'ofis-kirtasiye',
    'Ofis Aksesuarı': 'ofis-kirtasiye',
    'Paket Lastiği': 'ofis-kirtasiye',
    'Planlayıcı': 'ofis-kirtasiye',
    'Sekreterlik': 'ofis-kirtasiye',
    'Takvim': 'ofis-kirtasiye',
    'Zımba': 'ofis-kirtasiye',
    'Zarf': 'ofis-kirtasiye',
    'Yapıştırıcı': 'ofis-kirtasiye',
    'Makas': 'ofis-kirtasiye',
    'Maket Bıçak': 'ofis-kirtasiye',
    'Yaka Kartı & Aksesuarları': 'ofis-kirtasiye',
    'Çelik Para Kasası': 'ofis-kirtasiye',
    'Evrak Rafı': 'ofis-kirtasiye',

    // Kalem & Yazı
    'CD & DVD Kalemi': 'kalem-yazi',
    'Fosforlu Kalem': 'kalem-yazi',
    'Jel Mürekkepli Kalem': 'kalem-yazi',
    'Kalem Uçları': 'kalem-yazi',
    'Kalemtıraş': 'kalem-yazi',
    'Kalemtraş': 'kalem-yazi',
    'Keçeli Kalem': 'kalem-yazi',
    'Kurşun Kalem': 'kalem-yazi',
    'Mürekkep': 'kalem-yazi',
    'Prestij & Dolma Kalem': 'kalem-yazi',
    'Silgi': 'kalem-yazi',
    'Tükenmez Kalem': 'kalem-yazi',
    'Uçlu Kalem': 'kalem-yazi',
    'Kalem Kutusu': 'kalem-yazi',
    'Yazı Tahtası Kalemi': 'kalem-yazi',

    // Sanatsal
    'Boyama Seti': 'hobi-oyuncak',
    'Guaj Boya': 'hobi-oyuncak',
    'Kuru Boya Kalemi': 'hobi-oyuncak',
    'Pastel Boya': 'hobi-oyuncak',
    'Sanatsal Kağıt & Kalem': 'hobi-oyuncak',
    'Hamur Şekillendirici': 'hobi-oyuncak',
    'Çocuk Puzzle & Yapboz': 'hobi-oyuncak',
    'Blok Flüt': 'hobi-oyuncak',
    'Futbol Topu': 'hobi-oyuncak',
    'Tohumlar': 'hobi-oyuncak',
    'Tombala': 'hobi-oyuncak',

    // Kişisel Aksesuar
    'Bel Çantası': 'kisisel-aksesuar',
    'Cüzdan': 'kisisel-aksesuar',
    'El Çantası': 'kisisel-aksesuar',
    'Kapak & Kılıf': 'kisisel-aksesuar',
    'Kartlık': 'kisisel-aksesuar',
    'Omuz Çantası': 'kisisel-aksesuar',
    'Rozet': 'kisisel-aksesuar',
    'Taç': 'kisisel-aksesuar',
    'Tırnak Makası': 'kisisel-aksesuar',
    'Şemsiye': 'kisisel-aksesuar',
    'Makyaj & Takı Organizeri': 'kisisel-aksesuar',
    'Islak Mendil': 'kisisel-aksesuar',
    'Katı Sabun': 'kisisel-aksesuar',
    'Sıvı Sabun': 'kisisel-aksesuar',
    'Kolonya': 'kisisel-aksesuar',
    'Havlu': 'kisisel-aksesuar',
    'Ayna': 'kisisel-aksesuar',

    // Mutfak & İçecek
    'Bardak': 'mutfak-icecek',
    'Bardak Altlığı': 'mutfak-icecek',
    'Chemex': 'mutfak-icecek',
    'Dripper': 'mutfak-icecek',
    'El Rondosu': 'mutfak-icecek',
    'Kahve Fincanı': 'mutfak-icecek',
    'Kahve ve Baharat Öğütücü Değirmen': 'mutfak-icecek',
    'Karıştırıcı': 'mutfak-icecek',
    'Kağıt Peçete': 'mutfak-icecek',
    'Kupa': 'mutfak-icecek',
    'Limon Sıkacağı': 'mutfak-icecek',
    'Mug': 'mutfak-icecek',
    'Saklama Kabı': 'mutfak-icecek',
    'Sarımsak Ezici': 'mutfak-icecek',
    'Spor Matara': 'mutfak-icecek',
    'Suluk & Matara': 'mutfak-icecek',
    'Sürahi ve Karaf': 'mutfak-icecek',
    'Termos': 'mutfak-icecek',
    'Tirbuşon': 'mutfak-icecek',
    'Yağdanlık': 'mutfak-icecek',
    'Çırpıcı': 'mutfak-icecek',
    'Rende': 'mutfak-icecek',
    'Tuzluk & Biberlik': 'mutfak-icecek',

    // Teknoloji
    'Lazer Yazıcı': 'teknoloji',
    'Led Işık': 'teknoloji',
    'Mousepad': 'teknoloji',
    'Toner': 'teknoloji',
    'USB Bellek': 'teknoloji',
    'Powerbank': 'teknoloji',

    // Promosyon
    'Anahtarlık': 'promosyon-kurumsal',
    'Hediye Kutusu': 'promosyon-kurumsal',
    'Kumbara': 'promosyon-kurumsal',
    'Kırtasiye Seti': 'promosyon-kurumsal', // Can be ofis too, but typically sets are gifts

    // Özel Gün & Dekorasyon
    'Dekoratif Obje ve Biblo': 'dekorasyon',
    'Kar Küresi': 'ozel-gun',
    'Konsept Hediyelik': 'ozel-gun',
    'Mum & Kandil': 'dekorasyon',
    'Müzik Kutusu': 'dekorasyon',
    'Oda Kokusu': 'dekorasyon',
    'Yılbaşı Seti': 'ozel-gun',
    'Yılbaşı Süsü': 'ozel-gun',
};
